- project:
    name: centos-opstools/opstools-ansible-distgit
    check:
      jobs:
        - legacy-centos-opstools-rpmlint
        - legacy-centos-opstools-rpmbuild
        - legacy-centos-opstools-common-distgit-cbs-validate
